version: '3.8'

services:
  api:
    build: .
    container_name: learnus_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/learnus
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    restart: always
    volumes:
      - ./api_debug.log:/app/api_debug.log

  db:
    image: postgres:15
    container_name: learnus_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=learnus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
